### ISSUE TITLE
HP drain isn't 100% accurate

### ISSUE THREAD

**Issue by imsuck** [Wieku/danser-go#288]
**Describe the bug**
Danser thought I failed in the replay but when I use osu! to view the replay it's a pass.

**Files**
[replay](https://files.catbox.moe/14l3ej.osr)
[output](https://user-images.githubusercontent.com/49095435/193743967-a65ac965-544b-4625-a705-72c24c12836c.mp4)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/9702911/danser.log)

**Computer configuration:**
Operating System: EndeavourOS x86_64 (kernel: 5.19.12-arch1-1)
CPU: Intel(R) Core(TM) i5-4210U
GPU: Mesa Intel(R) HD Graphics 4400 (HSW GT2)
Sound Card: I'm not sure

**Comment by Wieku** [comment]
I don't think I can fix that one. After analyzing replay data it should be a fail, even in osu.

If we look at this screenshot:
![image](https://user-images.githubusercontent.com/5307179/194669840-a8c772fc-e6b2-489e-b24e-c5221451e0d4.png)

in osu, actually you get hit50:
![image](https://user-images.githubusercontent.com/5307179/194669892-d94cc91e-92a8-40c4-a78c-f348656d8597.png)

But for some reason osu! decides to change it to hit300 because that bar disappears almost instantly.

**Comment by Wieku** [comment]
Left was a osu! bug that seems to be fixed in newest cuttingedge, but it turned out issue also lies on danser's side.

**Comment by Wieku** [comment]
It's not yet pushed to dev branch but it appears to be fixed:

https://user-images.githubusercontent.com/5307179/197432928-4c97b3e1-5796-4bc9-83da-4f3597fa539c.mp4
