### ISSUE TITLE
ARM64 support?

### ISSUE THREAD

**Issue by ravener** [Wieku/danser-go#332]
I'd like to try to use this on my arm64 ubuntu server, but seems like it's not supported, there's only x64 binaries in release and if I try to build from source, there seems to be some x64 .so files in the source tree directly so that doesn't sound good either.

Any plans for arm64 linux support, or any quick hacks I can make it work from source?

**Comment by xjunko** [comment]
Theoretically it should work if you replace the bass's `*.so` files with the one that supports your architecture from the [un4seen website](https://www.un4seen.com/) (Files are in `/libs/<architecture>/*.so` format usually).
You need to replace `BASS`, `FX` and `MIX` respectively. 
Though, there might be other unrelated libraries that doesn't support arm64.

**Comment by Wieku** [comment]
Correct me wrong but I think it won't be worth it.

Pretty sure arm64 linux only supports OpenGL ES which misses required stuff for video creation. So it would use software rendering which is slow.

The only arm64 platform worth supporting would be Windows because its arm64 version has OpenGL->DX12 translation layer.

**Comment by k8ieone** [comment]
@Wieku GPU API support pretty much just depends on the GPU in question. Newer chips ship with Vulkan support and even older chips have "classic" OpenGL, not just ES. But like I said, it all depends on the particular GPU.

There are also ARM systems with PCI-E slots so desktop GPUs can be used too.

**Comment by NotJansel** [comment]
> There are also ARM systems with PCI-E slots so desktop GPUs can be used too.

Yea but is the entire situation stable on arm? Also arm is such a niche for this that it simply doesnt make sense right now to offer the builds as it may bring up more problems than solutions. So at this moment imo it still is not viable for offering arm64 Builds.

**Comment by k8ieone** [comment]
I understand ARM is not a mainstream platform by far. It most likely won't be any time in the near future. Even if you ended up providing ARM builds, my guess is that most people would only run them for fun instead of any practical reasons.

It's somewhat of a vicious cycle - lack of adoption because of software incompatibility and lack of software because of low adoption. ARM isn't the only example of this, RISC-V is going to have the same exact problem.

It is just my opinion that projects should aim to be architecture independent.

**Comment by Wieku** [comment]
> It is just my opinion that projects should aim to be architecture independent

I understand, but it's a niche program that generates a video for a weeb game or swings cursors in a "fun" way, not an archiver/cad/video editor.

Occasional dealing with AMD/Intel driver bullshit is enough to prevent me from having to maintain another ultra-niche platform and/or add another GPU API. If someone would help (if it won't require a complete refactor) then sure, I'm open to that, but I won't do that myself, I don't even have a platform to test it.

**Comment by nianweb-dev** [comment]
I have experimentally built a version that works on ARM64 architecture with added support for Raspberry Pi's hardware video encoders. If anyone is interested, I can conduct tests on my Raspberry Pi. During the porting process to ARM64 platform, numerous issues emerged that don't exist on x86 platforms - particularly the fragmented state of ARM platform drivers. I even had to downgrade the Linux kernel to properly utilize Raspberry Pi's hardware video encoder. Resolving these compatibility issues required significant effort, but based on my test results, the GPU and video encoder are now functioning correctly. However, rendering a 4-minute replay still takes up to 20 minutes. This seems impractical unless using external GPUs, but that would negate the advantages over simply running on x86 platforms. Therefore, my conclusion is that porting to ARM platforms isn't advisable - without hardware encoding, processing times would escalate to hour-long durations. Moreover, the video encoding API landscape on ARM platforms is chaotic (e.g., OpenMAX, MMAL, RKMPP), making comprehensive adaptation impossible. For those interested, the source code and pre-built binaries are available in my forked repository. I likely won't maintain this further, as ARM platforms' fragmentation means the build might fail on different hardware configurations.

![Image](https://github.com/user-attachments/assets/c2ff5efd-a0ea-4a9f-abab-f8d5f6118b42)

![Image](https://github.com/user-attachments/assets/37003e95-17aa-492f-af2e-2a79b88ce685)

![Image](https://github.com/user-attachments/assets/0d5fc971-a6be-413b-b4e9-5127956f01bf)

**Comment by k8ieone** [comment]
Oh yea, the video encoding/decoding situation is crazy. I pretty much ignore boards even having such functionality because it's just too much pain to get it going. In the end trying to make it work often isn't even worth it because the performance is bad.

The Pi is still one of the easiest platforms to make that work btw, especially on Raspberry Pi OS 💀 

@nianweb-dev How is the game's performance when playing a replay or doing cursor danse (without recording)?

**Comment by nianweb-dev** [comment]
Due to the Raspberry Pi's severely limited performance—even screen recording significantly strains system resources—I have disabled the VNC server and switched to using an HDMI capture card for recording. To achieve optimal performance, I overclocked the CPU to 1800MHz and the GPU to 750MHz. However, the Pi's performance remains subpar even without video encoding tasks. A sample recording captured via the HDMI setup is attached below.  

# 1080p

## cursor dance with ui  11fps

[maru.ciallo.work/2025/02/1739362731-2025-02-12_20-12-12.mp4](https://maru.ciallo.work/2025/02/1739362731-2025-02-12_20-12-12.mp4)

## cursor dance  30fps

[maru.ciallo.work/2025/02/1739362754-2025-02-12_20-15-19.mp4](https://maru.ciallo.work/2025/02/1739362754-2025-02-12_20-15-19.mp4)

## watch a replay  13fps

[maru.ciallo.work/2025/02/1739362742-2025-02-12_20-14-06.mp4](https://maru.ciallo.work/2025/02/1739362742-2025-02-12_20-14-06.mp4)

# 720p

## cursor dance 55fps wow

[maru.ciallo.work/2025/02/1739363853-2025-02-12_20-19-24.mp4](https://maru.ciallo.work/2025/02/1739363853-2025-02-12_20-19-24.mp4)

## watch a replay 25fps

[maru.ciallo.work/2025/02/1739363880-2025-02-12_20-20-35.mp4](https://maru.ciallo.work/2025/02/1739363880-2025-02-12_20-20-35.mp4)
